In [1]:
import numpy as np

In [2]:
a = np.array([[52,14],[74,87]])
print("Matrix A is:\n",a)
b = np.array([[84,98],[82,28]])
print("Matrix B is:\n",b)
s=a+b

Matrix A is:
 [[52 14]
 [74 87]]
Matrix B is:
 [[84 98]
 [82 28]]


In [3]:
print("Addition of Matrix A and Matrix B is:\n",s)

Addition of Matrix A and Matrix B is:
 [[136 112]
 [156 115]]
